# Change these first
owner: atomicjeep # Your GitHub organization or username
repo: up # Your GitHub repository name

# Add your sites here
sites:
  - name: Polymag.net
    url: https://www.polymag.net/
  - name: 3rd Horizons
    url: https://www.3rdhorizons.com/
  - name: horizons research
    url: https://www.horizonsresearch.org/
 

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
